### ISSUE TITLE
Error building jar file

### ISSUE THREAD

**Issue by Philipp0002** [wdavies973/VocalCord#1]
I tried to build the project with the command ".\gradlew jar" but the "build fails with an exeption":

`C:\Users\...\Desktop\VocalCord-master\src\main\java\com\prototype\vocalcord\tts\Responder.java:3: error: package com.sun.speech.freetts does not exist
import com.sun.speech.freetts.Voice;`

`C:\Users\fipsi\Desktop\VocalCord-master\src\main\java\com\prototype\vocalcord\tts\Responder.java:4: error: package com.sun.speech.freetts does not exist
import com.sun.speech.freetts.VoiceManager;`

`C:\Users\fipsi\Desktop\VocalCord-master\src\main\java\com\prototype\vocalcord\tts\Responder.java:5: error: package com.sun.speech.freetts.audio does not exist
import com.sun.speech.freetts.audio.SingleFileAudioPlayer;`

For everyone who has got this issue as well, _here's the fix_:
Go to the build.gradle file. 
In that file you need to change
`dependencies {
    compile 'commons-io:commons-io:2.6'`
to
`dependencies {
    compile fileTree(include: ['*.jar'], dir: 'lib')
    compile 'commons-io:commons-io:2.6'`

**Comment by wdavies973** [comment]
Added ```dependencies { compile fileTree(include: ['*.jar'], dir: 'lib') compile 'commons-io:commons-io:2.6'``` to the repo in the latest commit. Thanks for the help!
