### ISSUE TITLE
SingleFileAudioPlayer

### ISSUE THREAD

**Issue by SmooKboi** [wdavies973/VocalCord#2]
Gives me an NullPointer when setting the AudioPlayer with a SingleFileAudioPlayer

**Comment by wdavies973** [comment]
You're most likely having an issue with this [class](https://github.com/wdavies973/VocalCord/blob/master/src/main/java/com/prototype/vocalcord/tts/Responder.java). The file write directories are set to my PC (with dir "C:\\Users\\Will Davies\\ and so on). You'll have to change these to a valid location on your computer. Note, the voice res-ponder isn't fully functioning yet, so it may be better just to comment the code out.
